//USER TABLE **************** 1
GET http://hotel-restaurant.azurewebsites.net/api/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJhZG1pbiIsImV4cCI6Mzg3ODM3NDg5MX0.JUWsJ2AubP3x87ckw6EvJzTvqIwx0JZ_abcTbPfyWfA
###
GET http://localhost:8000/api/user/3
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODI4OTI1NH0.iB7MCfK7k_7SMMvlQ0sOljcrQiPzdL51UDHBXO-QeSY

GET http://localhost:8000/api/user?limit=2

  
###

PUT http://localhost:8000/api/user/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODI4OTI1NH0.iB7MCfK7k_7SMMvlQ0sOljcrQiPzdL51UDHBXO-QeSY

{
    "name": "Hamisi"
}
###
DELETE http://localhost:8000/api/user/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODI4OTI1NH0.iB7MCfK7k_7SMMvlQ0sOljcrQiPzdL51UDHBXO-QeSY
###
POST http://localhost:8000/auth/register
content-Type:application/json
  
  {
    "name": "Titus",
    "contact_phone": "+254714663322",
    "phone_verified": true,
    "email": "andreastailas96@gmail.com",
    "username":"andreas",
    "email_verified": true,
    "confirmation_code": "96075",
    "password": "andreas",
    "role":"user",
    "address": "Kagio",
    "Comment": "I am a senior developer"
  }
###
POST http://localhost:8000/auth/login
Content-Type:application/json
  
  {
    "username": "andreas",
    "password": "andreas"
  }
###

//RESTAURANT TABLE **************** 2
GET http://localhost:8000/restaurants
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODI4OTI1NH0.iB7MCfK7k_7SMMvlQ0sOljcrQiPzdL51UDHBXO-QeSY

###
GET http://localhost:8000/restaurant/7

###
GET http://localhost:8000/restaurant?limit=1

###
GET http://localhost:8000/restaurant?limit=0&offset=2

###
POST http://localhost:8000/restaurant
Content-Type: application/json

  {
    "id": 5,
    "name": "KFC",
    "street_address": "240",
    "zip_code": "241",
    "city_id": 1
  }

###
PUT http://localhost:8000/restaurant/5
Content-Type: application/json

{
    "name": "KFL"
}
 
###
DELETE http://localhost:8000/restaurant/12



###
//ADDRESS TABLE **************** 3
GET http://localhost:8000/addresses
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODI4OTI1NH0.iB7MCfK7k_7SMMvlQ0sOljcrQiPzdL51UDHBXO-QeSY

###
GET http://localhost:8000/address/5

###
GET http://localhost:8000/address?limit=7

###
GET http://localhost:8000/address?limit=7&offset=2

###
POST http://localhost:8000/address
Content-Type: application/json

  {
    "id": 8,
    "street_address_1": "240",
    "street_address_2": "241",
    "zip_code": "241",
    "delivery_instructions":"deliver on time",
    "user_id":2,
    "city_id": 1
  }
  

###
PUT http://localhost:8000/address/8
Content-Type: application/json
  
  {
      "city_id": 1
  }

###
DELETE http://localhost:8000/address/12


###
//CATEGORY TABLE **************** 4
GET http://localhost:8000/categories

###
GET http://localhost:8000/category/5

###
GET http://localhost:8000/category?limit=7

###
GET http://localhost:8000/category?limit=7&offset=2

###
POST http://localhost:8000/category
Content-Type: application/json

  {
    "id": 8,
    "name": "Fast Food"
  }


###
PUT http://localhost:8000/category/8
Content-Type: application/json

{
    "name": "Fast Food"
}


###
DELETE http://localhost:8000/category/8



###
//CITY TABLE **************** 5
GET http://localhost:8000/cities

###
GET http://localhost:8000/city/2

###
GET http://localhost:8000/city?limit=3

###
GET http://localhost:8000/city?limit=7&offset=2

###
POST http://localhost:8000/city
Content-Type: application/json

  {
    "id": 4,
    "name": "Nairobi",
    "state_id":2
  }


###
PUT http://localhost:8000/city/8
Content-Type: application/json

{
    "name": "Nairobi"
}


###
DELETE http://localhost:8000/city/40





###
//COMMENT TABLE **************** 6
GET http://localhost:8000/comments

###
GET http://localhost:8000/comment/5

###
GET http://localhost:8000/comment?limit=7

###
GET http://localhost:8000/comment?limit=7&offset=2

###
POST http://localhost:8000/comment
Content-Type: application/json

  {
    "id": 2,
    "order_id":8,
    "user_id": 2,
    "comment_text": "The food was great"
  }


###
PUT http://localhost:8000/comment/8
Content-Type: application/json

  {
    "id": 8,
    "comment_text": "The food was great"
  }


###
DELETE http://localhost:8000/comment/12



###
//DRIVER TABLE **************** 7
GET http://localhost:8000/drivers
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODI4OTI1NH0.iB7MCfK7k_7SMMvlQ0sOljcrQiPzdL51UDHBXO-QeSY

###
GET http://localhost:8000/driver/5


###
GET http://localhost:8000/drivers?limit=1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODI4OTI1NH0.iB7MCfK7k_7SMMvlQ0sOljcrQiPzdL51UDHBXO-QeSY

###
GET http://localhost:8000/driver?limit=7&offset=2


###
POST http://localhost:8000/driver
Content-Type: application/json

    {
    "id": 16,
    "car_make": "tayota",
    "car_model": "toyata",
    "car_year": 2016,
    "user_id": 5,
    "online": true,
    "delivering": true
  }


###
PUT http://localhost:8000/driver/16
Content-Type: application/json

{
    "car_make": "tayota",
    "car_model": "toyata",
    "car_year": 2016,
    "user_id": 5,
    "online": true,
    "delivering": true
}


###
DELETE http://localhost:8000/driver/17

###
POST http://localhost:8000/auth/register
content-Type:application/json
  
  {
    "id":"3",
    "userId":1,
    "username": "kiara",
    "password": "pass",
    "role": "driver"
  } 
###
POST http://localhost:8000/auth/login
Content-Type:application/json
  
  {
    "username": "kiara",
    "password": "pass"
  }
###
//STATE   TABLE **************** 8
GET http://localhost:8000/states
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODI4OTI1NH0.iB7MCfK7k_7SMMvlQ0sOljcrQiPzdL51UDHBXO-QeSY

###
GET http://localhost:8000/state/5

###
GET http://localhost:8000/state?limit=7

###
GET http://localhost:8000/state?limit=7&offset=2

###
POST http://localhost:8000/state
Content-Type: application/json

  {
    "id": 8,
    "name": "Nairobi",
    "code":"003"
  }


###
PUT http://localhost:8000/state/8
Content-Type: application/json

{
    "name": "Nairobi"
}


###
DELETE http://localhost:8000/state/40



###
//MENU_ITEM TABLE **************** 9
GET http://localhost:8000/menuitems


###
GET http://localhost:8000/menuitem/5


###
GET http://localhost:8000/menuitems?limit=7


###
GET http://localhost:8000/menuitems?limit=7&offset=2


###
POST http://localhost:8000/menuitem
Content-Type: application/json

  {
    "id": 8,
    "name": "Chips",
    "restaurant_id": 1,
    "category_id":2,
    "description":"hamburger",
    "ingredients":"meat and bread",
    "price": 200,
    "active":false
  }


###
PUT http://localhost:8000/menuitem/8
Content-Type: application/json

{
    "name": "Chips",
    "restaurant_id": 1,
    "price": 200
}


###
DELETE http://localhost:8000/menuitem/90



###
//ORDER TABLE ****************  10
GET http://localhost:8000/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxODI4OTI1NH0.iB7MCfK7k_7SMMvlQ0sOljcrQiPzdL51UDHBXO-QeSY

###
GET http://localhost:8000/order/19


###
GET http://localhost:8000/orders?limit=7


###
GET http://localhost:8000/orders?limit=7&offset=2


###
POST http://localhost:8000/order
Content-Type: application/json

  {
    "id": 8,
    "restaurant_id":"2" ,
    "estimated_delivery_time":"4/5/24",
    "actual_delivery_time": "4/5/24",
    "delivery_address_id":"2",
    "user_id": 1,
    "driver_id": 1,
    "price": "300",
    "discount": "30",
    "final_price": "270",
    "comment": "cash payment"
 
  }


###
PUT http://localhost:8000/order/8
Content-Type: application/json

{
    "user_id": 1,
    "restaurant_id": 1,
    "driver_id": 1
}

###

DELETE http://localhost:8000/order/12

###
GET http://localhost:8000/statuscatalogues
###
GET http://localhost:8000/statuscatalogue/2
###
GET http://localhost:8000/statuscatalogue?limit=7
###
GET http://localhost:8000/statuscatalogue?limit=7&offset=2
###
POST http://localhost:8000/statuscatalogue
Content-Type: application/json

{
  "id":4,
  "name":"processing"
}

###
PUT http://localhost:8000/statuscatalogue/3
Content-Type: application/json

{
  "name":"kenny"
}
###
DELETE http://localhost:8000/statuscatalogue/4

###
GET http://localhost:8000/restaurantowners
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJyZXN0YXVyYW50LW93bmVyIiwiZXhwIjoxNzE4Mjg4OTM5fQ.XJHIycjFQOSJeXVCAS8k0FspRMgFq4LN4nob_u6DtUU
###
GET http://localhost:8000/restaurantowner/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKb25lcyIsInJvbGUiOiJyZXN0YXVyYW50LW93bmVyIiwiZXhwIjoxNzE4Mjg4OTM5fQ.XJHIycjFQOSJeXVCAS8k0FspRMgFq4LN4nob_u6DtUU
###
GET http://localhost:8000/restaurantowner?limit=7
###
GET http://localhost:8000/restaurantowner?limit=7&offset=2
###
POST http://localhost:8000/restaurantowner
Content-Type: application/json

{
    "id": 3,
    "restaurant_id":4 ,
    "owner_id":2
}

###
PUT http://localhost:8000/restaurantowner/3
Content-Type: application/json

{
  "owner_id":"3"
}
###
DELETE http://localhost:8000/restaurantowner/3

###
POST http://localhost:8000/auth/register
content-Type:application/json
  
  {
    "id":"4",
    "userId":1,
    "username": "musiala",
    "password": "pass",
    "role": "restaurant-owner"
  } 
###
POST http://localhost:8000/auth/login
Content-Type:application/json
  
  {
    "username": "musiala",
    "password": "pass"
  }
###
###
GET http://localhost:8000/ordermenuitems
###
GET http://localhost:8000/ordermenuitem/2
###
GET http://localhost:8000/ordermenuitems?limit=7
###
GET http://localhost:8000/ordermenuitems?limit=7&offset=2
###
POST http://localhost:8000/ordermenuitem
Content-Type: application/json

{
    "id": 2,
    "order_id": 8,
    "menu_item_id": 1,
    "quantity": 4,
    "item_price": 200,
    "price": 200,
    "comment": "no discounts"
}

###
PUT http://localhost:8000/ordermenuitem/3
Content-Type: application/json

{
 "comment": "no discounts"
}
###
DELETE http://localhost:8000/ordermenuitem/2
  ###